version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: widget_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - widget_network
    env_file:
      - .env

  webserver:
    image: nginx:alpine
    container_name: widget_webserver
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8000}:80'
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - widget_network

networks:
  widget_network:
    driver: bridge
